apiVersion: v1
kind: Pod
metadata:
 name: pod-2
 labels:
   app: segundo-pod
spec:
  containers:
    - name: container-pod-2
      image: nginx:1.19.2
      ports:
      - containerPort: 80
      #criação do segundo pod